// Generated by gencpp from file manage_supermarket/add_product.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCT_H
#define MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCT_H

#include <ros/service_traits.h>


#include <manage_supermarket/add_productRequest.h>
#include <manage_supermarket/add_productResponse.h>


namespace manage_supermarket
{

struct add_product
{

typedef add_productRequest Request;
typedef add_productResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_product
} // namespace manage_supermarket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manage_supermarket::add_product > {
  static const char* value()
  {
    return "1f72cf40c5b6f23171699427bb08011e";
  }

  static const char* value(const ::manage_supermarket::add_product&) { return value(); }
};

template<>
struct DataType< ::manage_supermarket::add_product > {
  static const char* value()
  {
    return "manage_supermarket/add_product";
  }

  static const char* value(const ::manage_supermarket::add_product&) { return value(); }
};


// service_traits::MD5Sum< ::manage_supermarket::add_productRequest> should match
// service_traits::MD5Sum< ::manage_supermarket::add_product >
template<>
struct MD5Sum< ::manage_supermarket::add_productRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::add_product >::value();
  }
  static const char* value(const ::manage_supermarket::add_productRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::add_productRequest> should match
// service_traits::DataType< ::manage_supermarket::add_product >
template<>
struct DataType< ::manage_supermarket::add_productRequest>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::add_product >::value();
  }
  static const char* value(const ::manage_supermarket::add_productRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manage_supermarket::add_productResponse> should match
// service_traits::MD5Sum< ::manage_supermarket::add_product >
template<>
struct MD5Sum< ::manage_supermarket::add_productResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::add_product >::value();
  }
  static const char* value(const ::manage_supermarket::add_productResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::add_productResponse> should match
// service_traits::DataType< ::manage_supermarket::add_product >
template<>
struct DataType< ::manage_supermarket::add_productResponse>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::add_product >::value();
  }
  static const char* value(const ::manage_supermarket::add_productResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCT_H
