// Generated by gencpp from file manage_supermarket/add_productRequest.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCTREQUEST_H
#define MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct add_productRequest_
{
  typedef add_productRequest_<ContainerAllocator> Type;

  add_productRequest_()
    : name()
    , price(0.0)
    , stock(0)  {
    }
  add_productRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , price(0.0)
    , stock(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _price_type;
  _price_type price;

   typedef int64_t _stock_type;
  _stock_type stock;





  typedef boost::shared_ptr< ::manage_supermarket::add_productRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::add_productRequest_<ContainerAllocator> const> ConstPtr;

}; // struct add_productRequest_

typedef ::manage_supermarket::add_productRequest_<std::allocator<void> > add_productRequest;

typedef boost::shared_ptr< ::manage_supermarket::add_productRequest > add_productRequestPtr;
typedef boost::shared_ptr< ::manage_supermarket::add_productRequest const> add_productRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::add_productRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::add_productRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::add_productRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::add_productRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.price == rhs.price &&
    lhs.stock == rhs.stock;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::add_productRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::add_productRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::add_productRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::add_productRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::add_productRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0bf1f575588f48a654196b97d87deea";
  }

  static const char* value(const ::manage_supermarket::add_productRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0bf1f575588f48aULL;
  static const uint64_t static_value2 = 0x654196b97d87deeaULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/add_productRequest";
  }

  static const char* value(const ::manage_supermarket::add_productRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 price\n"
"int64 stock\n"
;
  }

  static const char* value(const ::manage_supermarket::add_productRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.price);
      stream.next(m.stock);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_productRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::add_productRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::add_productRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "price: ";
    Printer<double>::stream(s, indent + "  ", v.price);
    s << indent << "stock: ";
    Printer<int64_t>::stream(s, indent + "  ", v.stock);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_ADD_PRODUCTREQUEST_H
