// Generated by gencpp from file manage_supermarket/delete_product.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_DELETE_PRODUCT_H
#define MANAGE_SUPERMARKET_MESSAGE_DELETE_PRODUCT_H

#include <ros/service_traits.h>


#include <manage_supermarket/delete_productRequest.h>
#include <manage_supermarket/delete_productResponse.h>


namespace manage_supermarket
{

struct delete_product
{

typedef delete_productRequest Request;
typedef delete_productResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct delete_product
} // namespace manage_supermarket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manage_supermarket::delete_product > {
  static const char* value()
  {
    return "a4a7378fbe2cb6f7c7e5e0c2db2ce3e6";
  }

  static const char* value(const ::manage_supermarket::delete_product&) { return value(); }
};

template<>
struct DataType< ::manage_supermarket::delete_product > {
  static const char* value()
  {
    return "manage_supermarket/delete_product";
  }

  static const char* value(const ::manage_supermarket::delete_product&) { return value(); }
};


// service_traits::MD5Sum< ::manage_supermarket::delete_productRequest> should match
// service_traits::MD5Sum< ::manage_supermarket::delete_product >
template<>
struct MD5Sum< ::manage_supermarket::delete_productRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::delete_product >::value();
  }
  static const char* value(const ::manage_supermarket::delete_productRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::delete_productRequest> should match
// service_traits::DataType< ::manage_supermarket::delete_product >
template<>
struct DataType< ::manage_supermarket::delete_productRequest>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::delete_product >::value();
  }
  static const char* value(const ::manage_supermarket::delete_productRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manage_supermarket::delete_productResponse> should match
// service_traits::MD5Sum< ::manage_supermarket::delete_product >
template<>
struct MD5Sum< ::manage_supermarket::delete_productResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::delete_product >::value();
  }
  static const char* value(const ::manage_supermarket::delete_productResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::delete_productResponse> should match
// service_traits::DataType< ::manage_supermarket::delete_product >
template<>
struct DataType< ::manage_supermarket::delete_productResponse>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::delete_product >::value();
  }
  static const char* value(const ::manage_supermarket::delete_productResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_DELETE_PRODUCT_H
