// Generated by gencpp from file manage_supermarket/displayResponse.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_DISPLAYRESPONSE_H
#define MANAGE_SUPERMARKET_MESSAGE_DISPLAYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct displayResponse_
{
  typedef displayResponse_<ContainerAllocator> Type;

  displayResponse_()
    : output()  {
    }
  displayResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::manage_supermarket::displayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::displayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct displayResponse_

typedef ::manage_supermarket::displayResponse_<std::allocator<void> > displayResponse;

typedef boost::shared_ptr< ::manage_supermarket::displayResponse > displayResponsePtr;
typedef boost::shared_ptr< ::manage_supermarket::displayResponse const> displayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::displayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::displayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::displayResponse_<ContainerAllocator1> & lhs, const ::manage_supermarket::displayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::displayResponse_<ContainerAllocator1> & lhs, const ::manage_supermarket::displayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::displayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::displayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::displayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::displayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::displayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::displayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::displayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::manage_supermarket::displayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::displayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/displayResponse";
  }

  static const char* value(const ::manage_supermarket::displayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::displayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
;
  }

  static const char* value(const ::manage_supermarket::displayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::displayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct displayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::displayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::displayResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_DISPLAYRESPONSE_H
