// Generated by gencpp from file manage_supermarket/display.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_DISPLAY_H
#define MANAGE_SUPERMARKET_MESSAGE_DISPLAY_H

#include <ros/service_traits.h>


#include <manage_supermarket/displayRequest.h>
#include <manage_supermarket/displayResponse.h>


namespace manage_supermarket
{

struct display
{

typedef displayRequest Request;
typedef displayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display
} // namespace manage_supermarket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manage_supermarket::display > {
  static const char* value()
  {
    return "85fe84f26349bbc9952465d8d14f21f4";
  }

  static const char* value(const ::manage_supermarket::display&) { return value(); }
};

template<>
struct DataType< ::manage_supermarket::display > {
  static const char* value()
  {
    return "manage_supermarket/display";
  }

  static const char* value(const ::manage_supermarket::display&) { return value(); }
};


// service_traits::MD5Sum< ::manage_supermarket::displayRequest> should match
// service_traits::MD5Sum< ::manage_supermarket::display >
template<>
struct MD5Sum< ::manage_supermarket::displayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::display >::value();
  }
  static const char* value(const ::manage_supermarket::displayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::displayRequest> should match
// service_traits::DataType< ::manage_supermarket::display >
template<>
struct DataType< ::manage_supermarket::displayRequest>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::display >::value();
  }
  static const char* value(const ::manage_supermarket::displayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manage_supermarket::displayResponse> should match
// service_traits::MD5Sum< ::manage_supermarket::display >
template<>
struct MD5Sum< ::manage_supermarket::displayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::display >::value();
  }
  static const char* value(const ::manage_supermarket::displayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::displayResponse> should match
// service_traits::DataType< ::manage_supermarket::display >
template<>
struct DataType< ::manage_supermarket::displayResponse>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::display >::value();
  }
  static const char* value(const ::manage_supermarket::displayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_DISPLAY_H
