// Generated by gencpp from file manage_supermarket/displayRequest.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_DISPLAYREQUEST_H
#define MANAGE_SUPERMARKET_MESSAGE_DISPLAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct displayRequest_
{
  typedef displayRequest_<ContainerAllocator> Type;

  displayRequest_()
    : display()  {
    }
  displayRequest_(const ContainerAllocator& _alloc)
    : display(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _display_type;
  _display_type display;





  typedef boost::shared_ptr< ::manage_supermarket::displayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::displayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct displayRequest_

typedef ::manage_supermarket::displayRequest_<std::allocator<void> > displayRequest;

typedef boost::shared_ptr< ::manage_supermarket::displayRequest > displayRequestPtr;
typedef boost::shared_ptr< ::manage_supermarket::displayRequest const> displayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::displayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::displayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::displayRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::displayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.display == rhs.display;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::displayRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::displayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::displayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::displayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::displayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::displayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::displayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::displayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::displayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b769ce02fd717f35c9a1022ad1f7eca";
  }

  static const char* value(const ::manage_supermarket::displayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b769ce02fd717f3ULL;
  static const uint64_t static_value2 = 0x5c9a1022ad1f7ecaULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::displayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/displayRequest";
  }

  static const char* value(const ::manage_supermarket::displayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::displayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string display\n"
;
  }

  static const char* value(const ::manage_supermarket::displayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::displayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.display);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct displayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::displayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::displayRequest_<ContainerAllocator>& v)
  {
    s << indent << "display: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.display);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_DISPLAYREQUEST_H
