// Generated by gencpp from file manage_supermarket/edithargaResponse.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_EDITHARGARESPONSE_H
#define MANAGE_SUPERMARKET_MESSAGE_EDITHARGARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct edithargaResponse_
{
  typedef edithargaResponse_<ContainerAllocator> Type;

  edithargaResponse_()
    : harga_baru()  {
    }
  edithargaResponse_(const ContainerAllocator& _alloc)
    : harga_baru(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _harga_baru_type;
  _harga_baru_type harga_baru;





  typedef boost::shared_ptr< ::manage_supermarket::edithargaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::edithargaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct edithargaResponse_

typedef ::manage_supermarket::edithargaResponse_<std::allocator<void> > edithargaResponse;

typedef boost::shared_ptr< ::manage_supermarket::edithargaResponse > edithargaResponsePtr;
typedef boost::shared_ptr< ::manage_supermarket::edithargaResponse const> edithargaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::edithargaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::edithargaResponse_<ContainerAllocator1> & lhs, const ::manage_supermarket::edithargaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.harga_baru == rhs.harga_baru;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::edithargaResponse_<ContainerAllocator1> & lhs, const ::manage_supermarket::edithargaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::edithargaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::edithargaResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::edithargaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1536c4f1bef4e82e57f39fcbec3611e6";
  }

  static const char* value(const ::manage_supermarket::edithargaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1536c4f1bef4e82eULL;
  static const uint64_t static_value2 = 0x57f39fcbec3611e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/edithargaResponse";
  }

  static const char* value(const ::manage_supermarket::edithargaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string harga_baru\n"
;
  }

  static const char* value(const ::manage_supermarket::edithargaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.harga_baru);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct edithargaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::edithargaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::edithargaResponse_<ContainerAllocator>& v)
  {
    s << indent << "harga_baru: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.harga_baru);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_EDITHARGARESPONSE_H
