// Generated by gencpp from file manage_supermarket/editharga.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_EDITHARGA_H
#define MANAGE_SUPERMARKET_MESSAGE_EDITHARGA_H

#include <ros/service_traits.h>


#include <manage_supermarket/edithargaRequest.h>
#include <manage_supermarket/edithargaResponse.h>


namespace manage_supermarket
{

struct editharga
{

typedef edithargaRequest Request;
typedef edithargaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct editharga
} // namespace manage_supermarket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manage_supermarket::editharga > {
  static const char* value()
  {
    return "568b19a2ce38f33eeb2158cd05ab5278";
  }

  static const char* value(const ::manage_supermarket::editharga&) { return value(); }
};

template<>
struct DataType< ::manage_supermarket::editharga > {
  static const char* value()
  {
    return "manage_supermarket/editharga";
  }

  static const char* value(const ::manage_supermarket::editharga&) { return value(); }
};


// service_traits::MD5Sum< ::manage_supermarket::edithargaRequest> should match
// service_traits::MD5Sum< ::manage_supermarket::editharga >
template<>
struct MD5Sum< ::manage_supermarket::edithargaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::editharga >::value();
  }
  static const char* value(const ::manage_supermarket::edithargaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::edithargaRequest> should match
// service_traits::DataType< ::manage_supermarket::editharga >
template<>
struct DataType< ::manage_supermarket::edithargaRequest>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::editharga >::value();
  }
  static const char* value(const ::manage_supermarket::edithargaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manage_supermarket::edithargaResponse> should match
// service_traits::MD5Sum< ::manage_supermarket::editharga >
template<>
struct MD5Sum< ::manage_supermarket::edithargaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::editharga >::value();
  }
  static const char* value(const ::manage_supermarket::edithargaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::edithargaResponse> should match
// service_traits::DataType< ::manage_supermarket::editharga >
template<>
struct DataType< ::manage_supermarket::edithargaResponse>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::editharga >::value();
  }
  static const char* value(const ::manage_supermarket::edithargaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_EDITHARGA_H
