// Generated by gencpp from file manage_supermarket/edithargaRequest.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_EDITHARGAREQUEST_H
#define MANAGE_SUPERMARKET_MESSAGE_EDITHARGAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct edithargaRequest_
{
  typedef edithargaRequest_<ContainerAllocator> Type;

  edithargaRequest_()
    : name()
    , newHarga(0.0)  {
    }
  edithargaRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , newHarga(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _newHarga_type;
  _newHarga_type newHarga;





  typedef boost::shared_ptr< ::manage_supermarket::edithargaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::edithargaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct edithargaRequest_

typedef ::manage_supermarket::edithargaRequest_<std::allocator<void> > edithargaRequest;

typedef boost::shared_ptr< ::manage_supermarket::edithargaRequest > edithargaRequestPtr;
typedef boost::shared_ptr< ::manage_supermarket::edithargaRequest const> edithargaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::edithargaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::edithargaRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::edithargaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.newHarga == rhs.newHarga;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::edithargaRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::edithargaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::edithargaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::edithargaRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::edithargaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12292c6d7e97b6a8031e728a416590c9";
  }

  static const char* value(const ::manage_supermarket::edithargaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12292c6d7e97b6a8ULL;
  static const uint64_t static_value2 = 0x031e728a416590c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/edithargaRequest";
  }

  static const char* value(const ::manage_supermarket::edithargaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 newHarga\n"
;
  }

  static const char* value(const ::manage_supermarket::edithargaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.newHarga);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct edithargaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::edithargaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::edithargaRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "newHarga: ";
    Printer<double>::stream(s, indent + "  ", v.newHarga);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_EDITHARGAREQUEST_H
