// Generated by gencpp from file manage_supermarket/jual_productRequest.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_JUAL_PRODUCTREQUEST_H
#define MANAGE_SUPERMARKET_MESSAGE_JUAL_PRODUCTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manage_supermarket
{
template <class ContainerAllocator>
struct jual_productRequest_
{
  typedef jual_productRequest_<ContainerAllocator> Type;

  jual_productRequest_()
    : name()
    , amount(0)  {
    }
  jual_productRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , amount(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int64_t _amount_type;
  _amount_type amount;





  typedef boost::shared_ptr< ::manage_supermarket::jual_productRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manage_supermarket::jual_productRequest_<ContainerAllocator> const> ConstPtr;

}; // struct jual_productRequest_

typedef ::manage_supermarket::jual_productRequest_<std::allocator<void> > jual_productRequest;

typedef boost::shared_ptr< ::manage_supermarket::jual_productRequest > jual_productRequestPtr;
typedef boost::shared_ptr< ::manage_supermarket::jual_productRequest const> jual_productRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manage_supermarket::jual_productRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manage_supermarket::jual_productRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::jual_productRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.amount == rhs.amount;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manage_supermarket::jual_productRequest_<ContainerAllocator1> & lhs, const ::manage_supermarket::jual_productRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manage_supermarket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manage_supermarket::jual_productRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manage_supermarket::jual_productRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manage_supermarket::jual_productRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cfbb46c8c6a19dcda189badb6df95a3";
  }

  static const char* value(const ::manage_supermarket::jual_productRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cfbb46c8c6a19dcULL;
  static const uint64_t static_value2 = 0xda189badb6df95a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manage_supermarket/jual_productRequest";
  }

  static const char* value(const ::manage_supermarket::jual_productRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int64 amount\n"
;
  }

  static const char* value(const ::manage_supermarket::jual_productRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.amount);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jual_productRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manage_supermarket::jual_productRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manage_supermarket::jual_productRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "amount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.amount);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_JUAL_PRODUCTREQUEST_H
