// Generated by gencpp from file manage_supermarket/restock.msg
// DO NOT EDIT!


#ifndef MANAGE_SUPERMARKET_MESSAGE_RESTOCK_H
#define MANAGE_SUPERMARKET_MESSAGE_RESTOCK_H

#include <ros/service_traits.h>


#include <manage_supermarket/restockRequest.h>
#include <manage_supermarket/restockResponse.h>


namespace manage_supermarket
{

struct restock
{

typedef restockRequest Request;
typedef restockResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct restock
} // namespace manage_supermarket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manage_supermarket::restock > {
  static const char* value()
  {
    return "436aaeb2230331f8d91f79fac15bd4ce";
  }

  static const char* value(const ::manage_supermarket::restock&) { return value(); }
};

template<>
struct DataType< ::manage_supermarket::restock > {
  static const char* value()
  {
    return "manage_supermarket/restock";
  }

  static const char* value(const ::manage_supermarket::restock&) { return value(); }
};


// service_traits::MD5Sum< ::manage_supermarket::restockRequest> should match
// service_traits::MD5Sum< ::manage_supermarket::restock >
template<>
struct MD5Sum< ::manage_supermarket::restockRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::restock >::value();
  }
  static const char* value(const ::manage_supermarket::restockRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::restockRequest> should match
// service_traits::DataType< ::manage_supermarket::restock >
template<>
struct DataType< ::manage_supermarket::restockRequest>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::restock >::value();
  }
  static const char* value(const ::manage_supermarket::restockRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manage_supermarket::restockResponse> should match
// service_traits::MD5Sum< ::manage_supermarket::restock >
template<>
struct MD5Sum< ::manage_supermarket::restockResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manage_supermarket::restock >::value();
  }
  static const char* value(const ::manage_supermarket::restockResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manage_supermarket::restockResponse> should match
// service_traits::DataType< ::manage_supermarket::restock >
template<>
struct DataType< ::manage_supermarket::restockResponse>
{
  static const char* value()
  {
    return DataType< ::manage_supermarket::restock >::value();
  }
  static const char* value(const ::manage_supermarket::restockResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANAGE_SUPERMARKET_MESSAGE_RESTOCK_H
